services:
  # Blog Service
  post-service:
    build:
      context: ./post
    ports:
      - "4002:4002"
    depends_on:
      - kafka
      - post-db
    environment:
      MONGO_URL: mongodb://post-db:27017/postDB
      # - KAFKA=kafka:9092  # Changed from localhost:9092 to kafka:9092
      KAFKA: kafka:9092
    networks:
      - blog-network

  # Comment Service
  comment-service:
    build:
      context: ./comment
    ports:
      - "4003:4003"
    depends_on:
      - kafka
      - comment-db
    environment:
      MONGO_URL: mongodb://comment-db:27017/commentdb
      # - KAFKA=kafka:9092  # Changed from localhost:9092 to kafka:9092
      KAFKA: kafka:9092
    networks:
      - blog-network

  # User Service
  auth-service:
    build:
      context: ./auth
    ports:
      - "4001:4001"
    depends_on:
      - kafka
      - auth-db
    environment:
      JWT_TOKEN: mynameissecret
      MONGO_URL: mongodb://auth-db:27017/authdb
      KAFKA: kafka:9092  # Changed from localhost:9092 to kafka:9092
    networks:
      - blog-network

  # API Gateway
  gateway:
    build:
      context: ./gateway
    ports:
      - "7000:7000"
    depends_on:
      - post-service
      - comment-service
      - auth-service
    environment:
      - JWT_TOKEN=mynameissecret
      - URL_AUTH=http://auth-service:4001
      - URL_POST=http://post-service:4002
      - URL_COMMENT=http://comment-service:4003
    networks:
      - blog-network

  # MongoDB for Blog Service
  post-db:
    image: mongo:latest
    container_name: post-db
    volumes:
      - post-db-data:/data/db
    networks:
      - blog-network

  # MongoDB for Comment Service
  comment-db:
    image: mongo:latest
    container_name: comment-db
    volumes:
      - comment-db-data:/data/db
    networks:
      - blog-network

  # MongoDB for User Service
  auth-db:
    image: mongo:latest
    container_name: auth-db
    volumes:
      - auth-db-data:/data/db
    networks:
      - blog-network

  # Kafka Service
  kafka:
    # image: confluentinc/cp-kafka:latest
    # image: confluentinc/cp-kafka
    image: wurstmeister/kafka
    # image: kafka
    container_name: kafka
    ports:
      - "9092:9092"  # Expose Kafka to the host machine on port 9092 (optional)
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:9092"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_BROKER_ID: 1
    restart: always
    networks:
      - blog-network


  # Zookeeper Service
  zookeeper:
    # image: confluentinc/cp-zookeeper:latest
    image: wurstmeister/zookeeper
    # image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: always
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  post-db-data:
  comment-db-data:
  auth-db-data:
